# Generated by Django 5.0.2 on 2024-02-13 13:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
        migrations.DeleteModel(
            name="CustomUserManager",
        ),
    ]
