# Generated by Django 5.0.2 on 2024-02-15 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0002_delete_customuser_delete_customusermanager"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.PositiveIntegerField()),
                ("sex", models.CharField(max_length=10)),
                ("height", models.DecimalField(decimal_places=2, max_digits=5)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "bmi",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5),
                ),
                ("vaccination_history", models.TextField()),
                ("previous_medications", models.TextField()),
                ("procedures", models.TextField()),
                ("hospitalizations", models.TextField()),
                ("current_symptoms", models.TextField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
