# Generated by Django 5.0.2 on 2024-03-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_userprofile_cancer_screening_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="air_pollution_exposure",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="occupational_hazards",
            field=models.BooleanField(default=False),
        ),
    ]
